### ISSUE TITLE
GCP Batch resource deployment UX improvements

### ISSUE THREAD

**Issue by araghukas** [AgnostiqHQ/covalent-gcpbatch-plugin#37]
See [here](https://www.notion.so/agnostiq-public/OS-Resource-Deployment-UX-Review-bf7dbe6a025c40208b204c82739aca05?pvs=4#95c947e2bdac42b98f720cb6c74a810f) for notes.

<img src="https://drive.google.com/uc?id=107kzp8jEP5a9R-ehcNKpl1cucQDp7CLC">

- The following infra defaults are not used for resource creation
```
bucket_name
container_image_uri
service_account_email
vcpus
memory
time_limit
poll_freq
retries
cache_dir
access_token
```

- The `key_path` variables is NOT required, it has a [default value](https://github.com/AgnostiqHQ/covalent-gcpbatch-plugin/blob/397e6d6ff6768eaa140c7e70f11a04b1398f0607/covalent_gcpbatch_plugin/assets/infra/main.tf#L55)

- Some missing defaults could be specified in the help menu. For example, `region` [defaults to](https://github.com/AgnostiqHQ/covalent-gcpbatch-plugin/blob/397e6d6ff6768eaa140c7e70f11a04b1398f0607/covalent_gcpbatch_plugin/assets/infra/main.tf#L61C1-L62C1) `"us-east1"`

- The parameter named `vcpus` here is named `vcpu` in AWS Batch. Neither should be an infra parameter, else names should be resolved.

- The `prefix` parameter is used as a suffix.

```[tasklist]
### Tasks
- [ ] Review infra defaults NOT used for resource creation
- [ ] Update `key_path` so that default is displayed and is listed as not required
- [ ] Populate defaults/effective defaults for visibility in help menu
- [ ] Use `prefix` as a prefix or rename to `suffix`
```
